### ISSUE TITLE
Improve command line experience

### ISSUE THREAD

**Issue by joewittmer** [joewittmer/Morserino-32-Firmware-Updater#4]
Update the CLI to

   - Use named command line arguments instead of arguments in a specific order

        where arguments would be
            --port
            --rate
            --filename
            --erase
    
            and where --rate would have the options of [ 115200 (default), 460800, 921600 ]

Current valid commands are:

    update_m32 /dev/tty.usbserial-0001 921600 m32_v4.0.1.ino.wifi_lora_32_V2.bin erase
    update_m32 /dev/tty.usbserial-0001 921600 m32_v4.0.1.ino.wifi_lora_32_V2.bin

The new valid commands would be:

    update_m32 --port /dev/tty.usbserial-0001 --filename m32_v4.0.1.ino.wifi_lora_32_V2.bin --erase
    update_m32 --port /dev/tty.usbserial-0001 --filename m32_v4.0.1.ino.wifi_lora_32_V2.bin
    update_m32 --port /dev/tty.usbserial-0001 --rate 921600 --filename m32_v4.0.1.ino.wifi_lora_32_V2.bin --erase
    update_m32 --port /dev/tty.usbserial-0001 --rate 921600 --filename m32_v4.0.1.ino.wifi_lora_32_V2.bin

**Comment by oe1wkl** [comment]
Good idea to bring parameters in line with common usage. Maybe short options as recommended by GNU should also be allowed (like -p, -f, -r ...)? Have a look at https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html for GNU argument conventions...

**Comment by joewittmer** [comment]
Looking at minicom as an example, the names device and baudrate are used instead of port and rate. I think I like those names slightly better and will use those.

**Comment by joewittmer** [comment]
Actually I see now that the esptools library uses port and baud. It would make sense to be consistent so will use those names instead.

**Comment by joewittmer** [comment]
Hi @oe1wkl 

I've created a preview release available on the develop branch [here](https://github.com/joewittmer/Morserino-32-Firmware-Updater/tree/develop/release).

Could you let me know if you have any suggested changes before I complete the [PR](https://github.com/joewittmer/Morserino-32-Firmware-Updater/pull/18) and merge this into master?

btw, we now have builds for ubuntu since the project is being built on the GitHub servers.
